{% set name = "openvsp-code-eli" %}
{% set version = "2024.02.13" %}
{% set git_rev = "12c39c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ramcdona/Code-Eli.git
  git_rev: {{ git_rev }}
  patches:
    - 0001-cmake-packaging.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake  >=3.15
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/share/pkgconfig/ELI.pc                                        # [unix]
    - test -f $PREFIX/include/eli/code_eli.hpp                                      # [unix]
    - if not exist %PREFIX%\\Library\\include\\eli\\code_eli.hpp (exit 1)           # [win]

about:
  home: https://github.com/ramcdona/Code-Eli
  summary: 'Version of Code-Eli used in OpenVSP. Collection of C++ libraries that provide a variety of functionalities'
  license: EPL-1.0
  license_file: LICENSE.txt
  dev_url: https://github.com/ramcdona/Code-Eli

extra:
  recipe-maintainers:
    - martinRenou
